version: "2.1"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: rails_react_recipe
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - rails_react_recipe-postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - rails_react_recipe-redis:/var/lib/redis/data
  rails_react_recipe:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./rails_react_recipe:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env
  sidekiq:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: bundle exec sidekiq
    links:
      - postgres
      - redis
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - rails_react_recipe
    ports:
      - '8020:8020'
volumes:
  rails_react_recipe-postgres:
  rails_react_recipe-redis:
